---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: droplet
spec:
  encryptedData:
    users.acl: AgAo3pjB2SX3HvBWZ2HyJof9G2FTL9s6te/fHS8MAfHkO3Tkg1sIkmnVkJgUzAoSVnZ94MekBd8VkRwT85snBywcqp1HhAVUsjO4dxqSlonyl/9k24Dl8YIF0Ns2ETIeuF7rfpD2ZvsmnFRu+jqvXfRcCrPMI49cK7SydoNNkJpTFTteZ8qMU6ClhWrJq3J6pxjwrmi4cNjWwFufX9LXkDdnERq734PWDmV2aVt4mRHrPZG/6Jeb5A83uG+qtaJEqnh74IOV87+9ZwCCeoj2yUGeu8n57ryWjEPZNfAxUj97u3joJF0QaO2vY63pNO8qqhsY4+EFRBQqOmq8g/+yNA0z/61MOGW+aTfL0KJk188gS/O7jb6YTS2jHhVj5/3YqsOD76JRpLQloqVveQfEOJk2z3FGiL6fKcu7aaPQeybCBCfdktZg5Bhqhqq+UARXCJoxkfukZwZ00+ulXu5Nb5tOQADJpZVWolfhcnj2L/CgksmGJnneT2ydw0kx+9kH4r9+frAd51iNCCNwy3bemXZkK3rZb5fLz3O1+jZLLTRH8yXrhcUUF9Qt55BmnxZtsPSC+qjK/3Hc6d7OK+/GS+txQ8imcwJcaho15l0/DQgRxBAMXeepD6L8UWcqRVkXRbxJIAVhvvq99BZaN80ZZmOGkn5BPO7ihEpbg69Mye0Jubl66z5tHsSbeSnaqxdu3FMYZAecBMUg8bRg5tr+FYfozMbM6zH2oVwBuxWzOXJObCUsh01SLjOg+aNWeIfgGkeIDCxnjQBBszQayF6u6pJvLe2aS3eu124EDhfUo4FAXoz7Tw1wytgYSS7YtYS9DBRMCmgP+vJzSJw945xlJo13hH8qrALuVIl1vRWt/kdGciEFsTJO5fJqSikOo8uZ66eaKCxpRDVT/E4RYNDvb4GIXoPP7Nt8YdYjSPkZYjj6W0WjCnLcOjydfaFpjBWgAmg6cgCOeS33FeawTemazJ/Jgvb3w5Z/XFccbbys7ynwYlS7VuQHM7eORHevGNDiSt4oJu8Ol6zFAXfOVcoz4fEtkujHdKTLQtKsFUgfJdX050WR8/I+ygkS6wVdG5MYZHwiX3Q9rwIyt8DdupnuJ/K1Wese9P24Ts+H3UtbtHWXzQY03jeYfizXWrnUs8myawxrYH5tiIMji5qVJwrw8wyiVoWW6BpHABNcPNRVHRj4WzI/BoFemfVYREESNNayRqF9hrCcuNt7Ac/0+y1nJhZCxVv/Uq95x8jRM+davHa6fY2FoUKIeJrBWEokks31MeYqijmTYgtEDRQkIEdfVxbH/bJmtorXWbUAb7G0VqhgXjP8DnRwM9BL1RZtWndXspRFKYykybzSChgXwUAnoLEh093YXo3BQmixvtMVyvt2CH6brhRmk5EpQF48ie+j2Kthcg==
  template:
    metadata:
      name: redis-secrets
      namespace: droplet
