---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: droplet
spec:
  encryptedData:
    users.acl: AgAJl+ecoH2KlMU/EEfFu3jR2ep0yDC4ijYVlzca9ItvTudtYbj6UqnjbId+X7S6jPGY9jND3w/rodWFOA3OAXvv2yeApbaOBD7ZvyohERd/n+ahyuxx5KIOthRhd6d1b1Bpqu9sd1RKOxuPqVbRBDAcOVflKlhlgIlE++PDOdSXl9uKnyI26C2nP1pNmzg8b6fh7okr6JUP1rNQ5lhFeiyCVcxRYV7vdqcSqLjMV2W3iw6Z3cIE2Fwc81fSttfDpU0Wltc8MkLWeVJfK9XU0nD62y2KKLUKA8Mcfz7BpJydQk84NfpO3vLVR9S7KB9cx39rCh3zXyZu0MjI0nbKRBkaHxizDI4NI9v0klb8bU23NVCrbXZy9p+D2vEAZ/bMN1oWKdPLffKISB8FI5OhvPlzE/qABD6j1faTV1mhXjSET7s7Z0zJeeXUo3gAwr8WSqR/i6vvoG+Lt52R4TyA4x8q4krPRW2XZK+U36fAKgMS2zB1o82J4Jf2Tja+hbBf1Kntrqbq/oM9787Ps/PuKtlHCR3Tgs1f+lQvlZJNF4pOheO2LEz26xpQPJqgTxSOyhfIvWxZdDRXgP+R/y0Ba5VO9qvw9UvC7hIMzwEthRZ+JiB+Dk0mPsMn0QZniYDca25gXDz+dpqq7sAOrc45oO6Jq2R7bIhmDG+DaqEUsBfkE6BBQphlPqhZpNm4f1RanHCJr+Fkq4HF2BOOECYG2oBk8foNDepkSvyvu2EQQWSmQbtD736SHPFR/ZcvJ+TCnlXHM4FBZhkMY2n/VbEOmjzyhqzS4axJzmkrPUpxbDzD1v+tEzL/Y7OSQuZbwWc31LP1KROeae7vIIDJVHy/1AYfhVDIPoDd4QAFGuuSM+acyMWLEPcTpJiMT7XgVwxubhFocUDxodxeV2tBig5k3wRhBecvTSyN7Svohl3IbgJASTbmcJIA0FPopFivTe1VITIZb5P5pnmEdB2vmtSuuLXhJoOV4n+uXit8ui7goFfsSBOYd7pywR9r/LLE6snHnxJAxBB7z7m7eZhqNAI3Bdc1zoQ2zGyJz7cKoRUmMOFDZwc2X7JiGRHsPOfx5VYyM1pRHZopxOYVDtqZ6Y+tlyNiTqrR6tdEjp6WY6actO+i5988nuSTS1JKOAJ1PCpOY3NltSFLieVxTtyFP2HX4veq6mj3EwubKni/19MRXABQ2RwnCCNPYG7HV766sJTxc+EnH8Ddy6xuERDJly033mQPk3zAA0AC+c7kuqFGq+jvkA07667bwuYOrmwLvOX7XHIvU7dp/a7DEWrmFO7nwlX/1liV2wz7qijVAmP5/T/kzHMBZPvjXU1/DNUHB6taHaeJZ11skbJK0ROBmXVTB0ainR0poII/bi9eK3bmIHZPBgYKsMJTqFR4zeUM6zBgW0/JDg==
  template:
    metadata:
      name: redis-secrets
      namespace: droplet
