---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: droplet
spec:
  encryptedData:
    users.acl: AgB2OAq6MTPL7gXJgQ2OwREz1mfOxK3tC2X0Yz/Iny3gdoOTuJ/r8m8jCrDLZMmL7egtFZW9BDOVCbesi6C5H4gLKmgK5hh2gSYz3/6XioXLIiJ2KQwu361zwu8W3zX6QHB/Y13OcQzsld2WXtZI4W+wQ4KcxXP4wzKxVJwAwdbbXD1pBjdvcPR5ZYP16rJweafdp541IUogebfWp1TQ4VKS16XI1vCaQCtsJdTTdGlb5511wOclUrxQsZ+6xNcgmYO/2WLg4mDOZAkd18Nhqy4f8wf+bqrSwU4XRLk6LT9IikNxPJc55/rlgENL6ARfMzy/Feu3VCwOIYoXAcV5UZ9vee6fk9KumI7nxiwC4gsrINMt/gv+JduVKp2KQdVC6rrFuiUruuyb+QJI9VovUDpGbpD6KyvT9jyA0/rvlGxtR02dtkHvSrf819GPep2NR0Kz5zlVrRJYdI+kr8SGrzdprhlINoE0eScAInCYwD/zZ5RwXUpuOk8Oc9iuYI7IggiNlzC6jUbf4FHTMn2bCUdwe5gWT75gPx9Nbphgreocacb4GMDzzNLkmPq0lMIcFPzGGhfjhDinAmEdwYnizaSXCbQ9g+bZTkeIYV5ElkJ1wGx9lIUuHa4pDs6EkLSxDKftYdzpkY94QIvOB3SAovaLW7OLotgNoBDVq4OGNWfWn1PKsEMNJofzy/BAQgt1RTTW3cLiynn7ugfLi/ek70Oi8GZGDAFoY69p+HQCWG2Pu002m/dVL2hFfRUKGUws02NVkEOCcSowdGTMmflU/jiRYGAtCZq89B8eUWa8AIBui8TJTcGFHavTE9OYbQubMHlnWE4g52iQqo+f9BG1hDTMER5n9sf1agpETTtuZKyzpKLHXeQow0CANZbpFr6SqMicdawHzc5l+yCtSWy+l88uiGh/gPEqnB1xresD1VDcXHzE4HYOqS8dZpJ2IdpnsAp5J9Apk8XXIxisAGx0WhqBkkwJi2H+8YO+sOud5/YZgnSmVEtk6lDRyw4s3B+jNGCa3YrIqwOD5J8HJ/gHeGhTSEJLcjf7aytHWi1fWtYCH0o4xHBs/FAXZNqvL1AqQ2EGF3n9NQf+Oh00L/x/CtaLtLgFWrvH8xeszpwt9lrzX8U7wI5bOa/lmHrURBWeOPXU9AS2m1aLTnRAsVXGpoN2m+JSjkMoiV/NwEqXGp0vMKc8o8ecBCyvDerLuYbnrykHTJA1hgTTCew6vwh1jfgTvi+QQM18SUhiwFapoi/wh8OaJLnnN4LB7h2078+bPYYPUyZBT6iQ75cGsa5j9NkPA131krS3oPEyy5SHd18kLlXXXoXMAKVQJQnqe+k/QbugS5EYfU5jKFOF3/H69ROzm9OpQz6MFxcpV4W89G1kAQrs82BRWffRjgFexuhS5ty2fg==
  template:
    metadata:
      name: redis-secrets
      namespace: droplet
